#Constants
#Constants 
FEET_TO_METERS = 0.3048
MILES_TO_METERS = FEET_TO_METERS * 5280
ACRES_TO_METERS = 4046.86
SIMPLIFY_TOLERANCE = 100
MIN_SETBACK = 250
MAX_SETBACK = 3500
SETBACK_STEP = 250 #In Feet
MAX_HORIZONTAL = 3
HORIZONTAL_STEP = 1 #In Miles
setback_distances = seq(MIN_SETBACK, MAX_SETBACK, SETBACK_STEP) 
horizontal_distances = seq(0, MAX_HORIZONTAL, HORIZONTAL_STEP)
##
REMOVE_SMALL_AREAS = TRUE
MIN_WELLPAD_ACRES = 10 #In Acres
ADD_FEDERAl_LANDS = TRUE
SUBSET_FEDERAL_LANDS_TO_BLM = TRUE


USE_MICROSOFT_DATA = TRUE